//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/BulletInputAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BulletInputAsset: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BulletInputAsset()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BulletInputAsset"",
    ""maps"": [
        {
            ""name"": ""Bullet"",
            ""id"": ""786d74c8-30d3-4b5d-b264-be8768c03323"",
            ""actions"": [
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""ed053cbc-ef24-4a1c-90ff-cd6cdff6466e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""06e6e1dc-a208-4bbc-9960-b43eaca0d4aa"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Bullet
        m_Bullet = asset.FindActionMap("Bullet", throwIfNotFound: true);
        m_Bullet_Shoot = m_Bullet.FindAction("Shoot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bullet
    private readonly InputActionMap m_Bullet;
    private List<IBulletActions> m_BulletActionsCallbackInterfaces = new List<IBulletActions>();
    private readonly InputAction m_Bullet_Shoot;
    public struct BulletActions
    {
        private @BulletInputAsset m_Wrapper;
        public BulletActions(@BulletInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shoot => m_Wrapper.m_Bullet_Shoot;
        public InputActionMap Get() { return m_Wrapper.m_Bullet; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BulletActions set) { return set.Get(); }
        public void AddCallbacks(IBulletActions instance)
        {
            if (instance == null || m_Wrapper.m_BulletActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BulletActionsCallbackInterfaces.Add(instance);
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
        }

        private void UnregisterCallbacks(IBulletActions instance)
        {
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
        }

        public void RemoveCallbacks(IBulletActions instance)
        {
            if (m_Wrapper.m_BulletActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBulletActions instance)
        {
            foreach (var item in m_Wrapper.m_BulletActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BulletActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BulletActions @Bullet => new BulletActions(this);
    public interface IBulletActions
    {
        void OnShoot(InputAction.CallbackContext context);
    }
}
